library meilisearch;

export 'src/client.dart';
export 'src/index.dart';
export 'src/settings/_exports.dart';
export 'src/search_result.dart';
export 'src/filter_builder/_exports.dart';
export 'src/paginated_search_result.dart';
export 'src/query_parameters/documents_query.dart';
export 'src/query_parameters/cancel_tasks_query.dart';
export 'src/query_parameters/delete_tasks_query.dart';
export 'src/query_parameters/keys_query.dart';
export 'src/query_parameters/tasks_query.dart';
export 'src/query_parameters/indexes_query.dart';
export 'src/matching_strategy_enum.dart';
export 'src/key.dart';
export 'src/exception.dart';
export 'src/task.dart';
export 'src/swap_index.dart';
