name: Tests
on: [push, pull_request]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["2.7", "2.8"]
    container:
      image:  google/dart:${{ matrix.version }}
    services:
      meilisearch:
        image: getmeili/meilisearch:latest
        env:
          MEILI_MASTER_KEY: "masterKey"
          MEILI_NO_ANALYTICS: "true"
        ports:
          - "7700:7700"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: cd ./meilisearch && pub get
      - name: Test
        run: cd ./meilisearch && pub run test
        env:
          MEILI_SERVER: http://meilisearch:7700